Update README.md
ibpsa/project1-destest pull request #9
Opened 2020-12-27 22:23 UTC by HichamJohra

I have tried to make a more detailed explanation of what the DESTEST is all about

2020-12-28 08:48 UTC, MichaMans requested changes
@HichamJohra Thanks! This is a much better description then before 😃 I would suggest to integrate the links to the Modelica libraries and then merge it

2020-12-28 08:48 UTC, MichaMans commented on README.md
> +The goal of the IBPSA Project 1 is to develop a BIM/GIS and Modelica framework for building and community energy simulation. Within the IBPSA Project 1, the DESTEST (Work Package 3.1) aims at testing
Here I would add the links to the libraries and add a sentence like: The dedicated Modelica libraries can be found here: and they are based on the modelica-ibpsa (link) core library.

2020-12-28 19:50 UTC, HichamJohra commented
@MichaMans ok perfect.
Can you send me the links to the different Modelica libraries and the core one? Just to make sure I don't forget any and that I place the right link.

thanks

2020-12-29 08:49 UTC, MichaMans commented
@HichamJohra Here ist the core library with the links to the end-user libraries in the readme. https://github.com/ibpsa/modelica-ibpsa

2020-12-30 17:24 UTC, merged